### PR TITLE
Feat: Demo Trigger Attestation

### PR DESCRIPTION
**Pull request by agarant**
Provides a reference issuer implementation and enable demoing the [Trigger Attestation](https://github.com/WICG/attribution-reporting-api/blob/main/trigger_attestation.md) feature.

- Add a Private State Token issuer folder adapted from https://github.com/JackJey/trust-token-demo.
- In `adtech.js` call the executable when the Trigger Attestation header `Sec-Attribution-Reporting-Private-State-Token` is set on a conversion request.

### CODE REVIEW

**Review by maudnals — COMMENTED** [review]
Thanks @agarant! Appreciate the detailed README. I'll test it out, and until then just wanted to share a few quick observations:

* What happens if one tries to run the demo without going through the setup instructions listed [here](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-bfa2655fdbccf47e6ba1b70ad722aa46131575a32ef49a8b959c47d08a072b53)? To avoid breakage in that case, could we make the adtech server code that relates to attestation conditional, maybe based on whether a token is found? (i.e. [this code](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-f90d96efa77cd83ca4fc4b55fc954d09aa908e510ebde8e4a36ce659ebf74ad7R291) and [this code](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-f90d96efa77cd83ca4fc4b55fc954d09aa908e510ebde8e4a36ce659ebf74ad7R389)) 
* Could we add a few more comments in the adtech server code that relates to attestation? E.g. `// The token is ...`, `// Set cwd (which represents ...) to ...` (Granted, `adtech.js` should have more comments than it currently does; yet attestation being a complex feature, I think commenting that code could be super beneficial)

**Comment by agarant** [comment]
> What happens if one tries to run the demo without going through the setup instructions listed [here](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-bfa2655fdbccf47e6ba1b70ad722aa46131575a32ef49a8b959c47d08a072b53)? To avoid breakage in that case, could we make the adtech server code that relates to attestation conditional, maybe based on whether a token is found? (i.e. [this code](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-f90d96efa77cd83ca4fc4b55fc954d09aa908e510ebde8e4a36ce659ebf74ad7R291) and [this code](https://github.com/GoogleChromeLabs/trust-safety-demo/pull/43/files#diff-f90d96efa77cd83ca4fc4b55fc954d09aa908e510ebde8e4a36ce659ebf74ad7R389))

The setup instructions allow to re-build the c executable in case developers want to play with it. However, it remains optional as an executable is committed with this change. I can make this more clear in the Readme.

For the token to be present on the header, Chrome needs to have a key commitment for the demo's adtech origin. Which, based on the current plan, will require developers to run Chrome with a specific feature flag. We could add an example flag in the main readme that would work with the pre-generated keys & the live demo origin.

If the header is not there, attestation would be skipped. If it is there but invalid, it would log an error but would not block the main flow.

> Could we add a few more comments in the adtech server code that relates to attestation? E.g. // The token is ..., // Set cwd (which represents ...) to ... (Granted, adtech.js should have more comments than it currently does; yet attestation being a complex feature, I think commenting that code could be super beneficial)

Absolutely, I'll add more comments!

**Comment by maudnals** [comment]
Thanks Anthony!

> We could add an example flag in the main readme that would work with the pre-generated keys & the live demo origin.

1. Sounds good!

> If the header is not there...

2. IMU you're referring to `sec-attribution-reporting-private-state-token`- Correct?

> If the header is not there attestation would be skipped. 
> If it is there but invalid, it would log an error but would not block the main flow.

3. IMU if I'm **not** running Chrome with report verification flags, then the header will be absent. Correct?
4. In what case would the header be present but invalid - IMU that happens if the report is likely to be fraudulent, but what else?

5. A heads-up that some comments in this PR may need editing if the [renaming](https://github.com/WICG/attribution-reporting-api/pull/720) goes through.

**Comment by agarant** [comment]
Closing as Report Verification was removed https://github.com/WICG/attribution-reporting-api/pull/1366

**Pull request closed without merging**
